### ISSUE TITLE
Recent Docker image changes create unusable image

### ISSUE THREAD

**Issue by aashley** [prometheus-community/ipmi_exporter#100]
The recent updates to the Dockerfile produce an unusable image as the FreeIPMI tools are not included in the resulting image so the exporter can't retrieve any data.

This was caused by e649afb00813397ff9130b749b7c4e2395a7b07a

**Comment by bitfehler** [comment]
That is indeed a problem :sweat_smile: 
@SuperQ do you know either the best way to add software to the standard prometheus images or if there are other exporters that have a similar need? I looked at https://github.com/prometheus/busybox/blob/master/glibc/Dockerfile and looks like you copy over stuff from Debian there, but that seems pretty cumbersome for something more involved like FreeIPMI?

**Comment by bitfehler** [comment]
Hey there! I just released version 1.5.2, which should fix this. Currently there is only amd64 images, I hope that's what you were trying to use? If you can, please let me know if the new images work for you now!

**Comment by aashley** [comment]
Most of my cluster is arm64 but I have an amd64 node for things that don't make arm64 images available.

This has worked and is up and retrieving data again.

**Comment by bitfehler** [comment]
Thanks! I'll try to bring back the ARM images ASAP!
