### ISSUE TITLE
Failed to collect chassis data

### ISSUE THREAD

**Issue by nzubarev122** [prometheus-community/ipmi_exporter#102]
Hello

ts=2022-03-10T14:25:21.433Z caller=collector_chassis.go:53 level=error msg="Failed to collect chassis data" target=5.39.221.37 error="error running ipmi-chassis: exec: \"ipmi-chassis\": executable file not found in $PATH: "

whereis ipmi-chassis ?

**Comment by bitfehler** [comment]
Hi there!

Are you using the docker image? If not, what OS are you running the exporter on?

**Comment by nzubarev122** [comment]
> Hi there!
> 
> Are you using the docker image? If not, what OS are you running the exporter on?

CentOS Linux release 7.9.2009 (Core) , without docker

**Comment by bitfehler** [comment]
`ipmi-chassis` is part of FreeIPMI. Do you have FreeIPMI installed? For example, do you have a `ipmimonitoring` executable in your path?
