### ISSUE TITLE
version info missing

### ISSUE THREAD

**Issue by itzsimpl** [prometheus-community/ipmi_exporter#105]
When built via `go install github.com/prometheus-community/ipmi_exporter@v1.5.2` the resulting `ipmi_exporter` does not report any version information
```
$ ipmi_exporter --version
ipmi_exporter, version  (branch: , revision: )
  build user:       
  build date:       
  go version:       go1.18
  platform:         linux/amd64
```

**Comment by SuperQ** [comment]
You need to use `make build` in order to have these values added.
