### ISSUE TITLE
Running in Kubernetes

### ISSUE THREAD

**Issue by christianknell** [prometheus-community/ipmi_exporter#109]
Are there any plans to provide an Helm Chart to install the IPMI Exporter in a Kubernetes cluster?

**Comment by bitfehler** [comment]
Not from my side, no. But if someone wants to make one, https://github.com/prometheus-community/helm-charts has some inspiration and would also be a good home for that.

**Comment by lexfrei** [comment]
@christianknell it's merged! Feel free to test it :)

**Comment by bitfehler** [comment]
Closing this, with https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-ipmi-exporter being the community-maintained, recommended solution
