### ISSUE TITLE
Exclude sensors ids to be define at a target level

### ISSUE THREAD

**Issue by nwies** [prometheus-community/ipmi_exporter#118]
Hello,

Could you please define the exclude ID at "target" level and a global one?
I'm trying to set a ipmi exporter on 4 different systems (idrac7/ilo4/idrac9); I'm only need power and temperature. But each system had his own sensor Id.
For example,  97 will be the power sensor Id on one system

Thanks a lot.

**Comment by bitfehler** [comment]
Hi there,
the "exclude IDs" are already specified at the module level (see [example](https://github.com/prometheus-community/ipmi_exporter/blob/master/ipmi_remote.yml#L32)), which can be translated to per-target. This seems to be what you want?

Are you using one exporter to scrape the four systems remotely, or are you running one exporter on each system?

**Comment by nwies** [comment]
Hello,

Thanks for your reply.
Yes, I would like to have the "exclude IDS" at a per-target level.
You are right, I'm planning to use only one exporter to scrape the 4 systems remotely.

BR

**Comment by bitfehler** [comment]
Ok, cool. Then you'll need to prepare an exporter config file with four modules, similar to the example, one module per host. It is common practice, though not required, to name the modules after the addresses of your targets.

You will then need to configure your _Prometheus_ server to scrape each instance using the correct module parameter. If you follow the above mentioned naming convention, you can do it with a label rewrite, as documented at the very bottom of [this section](https://github.com/prometheus-community/ipmi_exporter/blob/master/docs/configuration.md#remote-metrics), but it's best to read the entire section carefully.

This way, you'll have one module per target, allowing you specify different sensor excludes for each one.

**Comment by nwies** [comment]
hello,

Please find my ipmi.ymL
[ipmi_NWIES.yml.txt](https://github.com/prometheus-community/ipmi_exporter/files/9241447/ipmi_NWIES.yml.txt)
For now, I only prep the file and did not start the exporter itself

**Comment by nwies** [comment]
Hello,

Thanks for pointing the idea of drop metrics from prometheus side.

Please find the complete workaround:

I used the file ipmi_NWIES.yml_V2.txt : the main difference is the unset of default user and password.

I add on my prometheus.yml the file prometheus_NWIES.yml.txt :
For each target:
I add to define a "target" job params and a "module" job params.
I hardcode the instance full text replacement.
the "targets" line is the server running the ipmi_exporter
[ipmi_NWIES.yml__V2.txt](https://github.com/prometheus-community/ipmi_exporter/files/9255580/ipmi_NWIES.yml__V2.txt)
[prometheus_NWIES.yml.txt](https://github.com/prometheus-community/ipmi_exporter/files/9255581/prometheus_NWIES.yml.txt)

So now, the only "ipmi*" metrics from my prometheus are this one:
![image](https://user-images.githubusercontent.com/10389749/182730034-786d049f-ef49-48cb-83e5-1a54d105b99c.png)


You can close this issue if you want.
BR

**Comment by bitfehler** [comment]
Cheers, glad it worked.
