### ISSUE TITLE
Multiple commands specified Error

### ISSUE THREAD

**Issue by wilula** [prometheus-community/ipmi_exporter#121]
Hello i am trying to provide additional argument for dcmi, but it fails to scrap with Multiple commands specified error. Everything else seems to work fine. Thanks in advance for help :)
This is config for this module
```192.168.1.1:
                user: "user"
                pass: "password"
                driver: "LAN_2_0"
                privilege: "admin"
                collectors:
                - dcmi
                - bmc
                - chassis
                - ipmi
                custom_args:
                        dcmi:
                        - "--get-system-power-statistics"  ```

**Comment by bitfehler** [comment]
Hello,

it is very hard to read your config snippet, it would be better to paste it in a proper code block (in triple backticks).

From what I can tell, you want to pass `--get-system-power-statistics` as additional argument to the `ipmi-dcmi` executable (which is used by the `dcmi` collector). However, there is no need for this: the collector already passes this argument by default (see [collector_dcmi.go](https://github.com/prometheus-community/ipmi_exporter/blob/master/collector_dcmi.go#L47)).

What is it that made you try this in the first place? Is something not working?

**Comment by wilula** [comment]
Sorry, i corrected the code block. When i delete the additional argument, exporter don't return any error but i can't see the desired metrics (current power, maximum power etc.). When i launch the ipmi-dcmi directly with --get-system-power-statistics this parameters are returned from ipmi. Could You have any idea why the exporter won't return them ?

**Comment by bitfehler** [comment]
can you please post the exact ipmi-dcmi command you are executing (minus any passwords of course) and the output?

**Comment by wilula** [comment]
Yes of course :) 
The command:
 ```/usr/sbin/ipmi-dcmi -h 10.11.0.216 -u -P --get-system-power-statistic```
The output:
```Current Power                        : 119 Watts
Minimum Power over sampling duration : 59 watts
Maximum Power over sampling duration : 927 watts
Average Power over sampling duration : 104 watts
Time Stamp                           : 08/30/2022 - 09:22:16
Statistics reporting time period     : 3442792824 milliseconds
Power Measurement                    : Active
```
I dont' know if this is correct becouse the metrics are returned in diffrent time frame but ipmi_dcmi_power_consumption_watts is the same value as Current Power here ?

**Comment by bitfehler** [comment]
Ah, I see now. Yes, `ipmi_dcmi_power_consumption_watts` is "Current Power". The reason that you don't see the other metrics is that the exporter ignores them, because they are aggregations, so they make no sense in a metrics database. You can easily get minimum/maximum/average power consumption for any time frame you see fit by using the respective Prometheus functions on your `ipmi_dcmi_power_consumption_watts` time series.

**Comment by wilula** [comment]
You are right, I just stated playing with additional arguments and didn't connected dots :) Thank You for clearing this out !
