### ISSUE TITLE
Missing several Linux tar balls on latest release

### ISSUE THREAD

**Issue by treydock** [prometheus-community/ipmi_exporter#128]
It appears like Linux arch like ppc64le is available for 1.5.1 but not 1.6.1.  Based on .promu.yml all Linux arches should be getting built.

**Comment by bitfehler** [comment]
Both releases have the exact same number of assets, and ppc64le is right there: https://github.com/prometheus-community/ipmi_exporter/releases/download/v1.6.1/ipmi_exporter-1.6.1.linux-ppc64le.tar.gz

**Comment by treydock** [comment]
I must have somehow missed it when looking at release page.  Sorry for the noise.
