### ISSUE TITLE
ipmi exporter Can't collect data

### ISSUE THREAD

**Issue by icejin1977** [prometheus-community/ipmi_exporter#136]
Hi, everyone!
I have already deployed ipmi exporter and the service starts normally on port 9290, but the hardware information of the device is not collected on grafana. monitoring device ipmi exporter how to configure correctly, thanks a lot! Looking forward to good news from everyone!

**Comment by MapleWhiteZZZ** [comment]
have a try，  :9290?target=ip;  otherwise,  you should check the grafana infomation

**Comment by icejin1977** [comment]
Ok, thanks
