### ISSUE TITLE
ipmi_ctx_open_outofband: command invalid or unsupported

### ISSUE THREAD

**Issue by Gaozizhong** [prometheus-community/ipmi_exporter#141]
ipmi_ctx_open_outofband appears in the logs when ipmi-exporter is pulling data out: command invalid or unsupported error. Services such as ipmi-sensors must specify -D to pull data correctly. I do not know the cause. Is there a way to modify the server to solve this problem?

**Comment by Gaozizhong** [comment]
ipmi-locate

```
[root@CVM-101 ~]# ipmi-locate 
Probing KCS device using DMIDECODE... done
IPMI Version: 2.0
IPMI locate driver: DMIDECODE
IPMI interface: KCS
BMC driver device: 
BMC I/O base address: 0xCA2
Register spacing: 1

Probing SMIC device using DMIDECODE... FAILED

Probing BT device using DMIDECODE... FAILED

Probing SSIF device using DMIDECODE... FAILED

Probing KCS device using SMBIOS... done
IPMI Version: 2.0
IPMI locate driver: SMBIOS
IPMI interface: KCS
BMC driver device: 
BMC I/O base address: 0xCA2
Register spacing: 1

Probing SMIC device using SMBIOS... FAILED

Probing BT device using SMBIOS... FAILED

Probing SSIF device using SMBIOS... FAILED

Probing KCS device using ACPI... FAILED

Probing SMIC device using ACPI... FAILED

Probing BT device using ACPI... FAILED

Probing SSIF device using ACPI... FAILED

Probing KCS device using PCI... FAILED

Probing SMIC device using PCI... FAILED
```

**Comment by Gaozizhong** [comment]
Thank you. I've solved that problem and now I have a new one. How do I keep ipmi_exporter with both IPMI1.5 and IPMI2.0?

**Comment by bitfehler** [comment]
You can have different modules in your config which use different settings (e.g. for driver). See https://github.com/prometheus-community/ipmi_exporter/blob/master/ipmi_remote.yml for an example. You will have to make sure in your prometheus config (not the exporter config) sets the module parameter accordingly when scraping. https://github.com/prometheus-community/ipmi_exporter/blob/master/docs/configuration.md has more details.

**Comment by Gaozizhong** [comment]
thanks for your help
