### ISSUE TITLE
No metrics for some of the chassis states

### ISSUE THREAD

**Issue by petshopjke1337** [prometheus-community/ipmi_exporter#144]
Recently we started using ipmi_exporter and found out that there is no metrics for **Drive Fault** and **Cooling/fan fault** states

> System Power                        : on
> Power overload                      : false
> Interlock                           : inactive
> Power fault                         : false
> Power control fault                 : false
> Power restore policy                : Restore
> Last Power Event                    : unknown
> Chassis intrusion                   : inactive
> Front panel lockout                 : inactive
> Drive Fault                         : false
> Cooling/fan fault                   : false
> Chassis Identify state              : off
> Power off button                    : enabled
> Reset button                        : enabled
> Diagnostic Interrupt button         : enabled
> Standby button                      : enabled
> Power off button disable            : unallowed
> Reset button disable                : unallowed
> Diagnostic interrupt button disable : unallowed
> Standby button disable              : unallowed

**Comment by bitfehler** [comment]
Thanks for the patch!
