### ISSUE TITLE
Handling passwords securely

### ISSUE THREAD

**Issue by danishka** [prometheus-community/ipmi_exporter#155]
The use-case is monitor bunch of remote IPMI interfaces and each has different password.
How to store password in a secure manner in IPMI remote config?

**Comment by bryanzl** [comment]
me too

**Comment by bitfehler** [comment]
Not sure I understand the question. The same way you handle other sensitive data? This question is out of scope of maintaining this software, it depends heavily on your environment, etc. If you have more specific questions relating to the exporter itself, feel free to reopen.
