### ISSUE TITLE
ipmi_ctx_open_outofband_2_0: internal system error

### ISSUE THREAD

**Issue by lklkxcxc** [prometheus-community/ipmi_exporter#188]
ipmi_exporter report error:
```
ts=2024-03-19T07:30:34.229Z caller=collector_bmc.go:53 level=error msg="Failed to collect BMC data" target=172.21.21.23 error="error running bmc-info: exit status 1: ipmi_ctx_open_outofband_2_0: internal system error\n"
ts=2024-03-19T07:30:34.239Z caller=collector_ipmi.go:151 level=error msg="Failed to collect sensor data" target=172.21.21.23 error="error running ipmimonitoring: exit status 1: ipmi_ctx_open_outofband_2_0: internal system error\n"
ts=2024-03-19T07:30:34.245Z caller=collector_chassis.go:65 level=error msg="Failed to collect chassis data" target=172.21.21.23 error="error running ipmi-chassis: exit status 1: ipmi_ctx_open_outofband_2_0: internal system error\n"
```
freeipa version: freeipmi-1.6.14-2.el8.x86_64
ipmi_exporter version: 1.8.0

**Comment by bitfehler** [comment]
The error is from FreeIPMI, this is outside the scope of this exporter. If you can provide a working command line invocation of e.g. `bmc-info` I can help you translate that into a corresponding exporter config.

**Comment by lklkxcxc** [comment]
@bitfehler thanks！bmc version：1.08.000000
[root@monitor ~]# bmc-info -h 172.21.21.36 -u admin -p xxxx  -D LAN
ipmi_ctx_open_outofband: command invalid or unsupported

**Comment by bitfehler** [comment]
> [root@monitor ~]# bmc-info -h 172.21.21.36 -u admin -p xxxx  -D LAN
> ipmi_ctx_open_outofband: command invalid or unsupported

This is the one you'll have to get to work, which I cannot help you with. I can give you one hint, though: you most likely want `LAN_2_0`, not `LAN`.
