### ISSUE TITLE
ipmimonitoring获取到的数据有重复内容

### ISSUE THREAD

**Issue by Gaozizhong** [prometheus-community/ipmi_exporter#189]
80  | FAN1_F_Speed     | Fan                      | Nominal  | 6000.00    | RPM   | 'OK'
81  | FAN2_F_Speed     | Fan                      | Nominal  | 6000.00    | RPM   | 'OK'
82  | FAN3_F_Speed     | Fan                      | Nominal  | 6000.00    | RPM   | 'OK'
83  | FAN4_F_Speed     | Fan                      | Nominal  | 6000.00    | RPM   | 'OK'
84  | FAN1_R_Speed     | Fan                      | Nominal  | 5100.00    | RPM   | 'OK'
85  | FAN2_R_Speed     | Fan                      | Nominal  | 5100.00    | RPM   | 'OK'
86  | FAN3_R_Speed     | Fan                      | Nominal  | 4950.00    | RPM   | 'OK'
87  | FAN4_R_Speed     | Fan                      | Nominal  | 5100.00    | RPM   | 'OK'
80  | FAN1_F_Speed     | Fan                      | Nominal  | 6000.00    | RPM   | 'OK'
81  | FAN2_F_Speed     | Fan                      | Nominal  | 6000.00    | RPM   | 'OK'
82  | FAN3_F_Speed     | Fan                      | Nominal  | 6000.00    | RPM   | 'OK'
83  | FAN4_F_Speed     | Fan                      | Nominal  | 6000.00    | RPM   | 'OK'
84  | FAN1_R_Speed     | Fan                      | Nominal  | 5100.00    | RPM   | 'OK'
85  | FAN2_R_Speed     | Fan                      | Nominal  | 5100.00    | RPM   | 'OK'
86  | FAN3_R_Speed     | Fan                      | Nominal  | 4950.00    | RPM   | 'OK'
87  | FAN4_R_Speed     | Fan                      | Nominal  | 5100.00    | RPM   | 'OK'

**Comment by bitfehler** [comment]
It looks like this is the output of `ipmimonitoring`?  If so, the problem must bei either with FreeIPMI or with the IPMI implementation of the device you are scraping?

**Comment by Gaozizhong** [comment]
是的，是ipmimonitoring的输出。但是用ipmitool就不会出现重复呢
