### ISSUE TITLE
Version 1.8.0 has wrong release date

### ISSUE THREAD

**Issue by hoperays** [prometheus-community/ipmi_exporter#193]
<img width="1216" alt="图片" src="https://github.com/prometheus-community/ipmi_exporter/assets/15916907/4ca72289-7186-4f2a-8590-4719b1f8675f">

**Comment by hoperays** [comment]
Supplement the release link: https://github.com/prometheus-community/ipmi_exporter/releases/tag/v1.8.0

**Comment by bitfehler** [comment]
Fixed, thanks.
