### ISSUE TITLE
Publish docker image to docker hub?

### ISSUE THREAD

**Issue by ibigbug** [prometheus-community/ipmi_exporter#70]
is there an existing image on docker hub or anywhere so that everyone don't need to build their own?

**Comment by bitfehler** [comment]
There isn't. I personally don't see the use for Docker images to run a single executable, hence I don't have any plans to maintain a publishing pipeline for those.

**Comment by ibigbug** [comment]
I think one use case could potentially be running the program directly on a container platform such as Portainer or K8S etc without having to build the image manually by everyone?

**Comment by SuperQ** [comment]
@bitfehler We publish all the Prometheus exporters as containers. It makes sense to do it here as well.

If you want, I can setup the basics of the Prometheus promu/circleci pipelines to handle this. I just need you or maybe @matthiasr top click some buttons and add some ENVs.

**Comment by matthiasr** [comment]
Unfortunately we cannot use CircleCI on the soundcloud org. We could move the exporter to the prometheus-community org now that that's a thing?

**Comment by bitfehler** [comment]
> We could move the exporter to the prometheus-community org now that that's a thing?

Sounds reasonable. I will look into this next.

**Comment by bitfehler** [comment]
Update: this project is now part of the prometheus-community org, so we should be able to make some progress here shortly

**Comment by jonkerj** [comment]
Any news on this? I'd like to run the exporter from my Kubernetes cluster, which could really benefit from published containers.

**Comment by SuperQ** [comment]
It's done with the latest release.

https://hub.docker.com/r/prometheuscommunity/ipmi-exporter

**Comment by bitfehler** [comment]
Talk about timing ;)
