### ISSUE TITLE
Unable to start container

### ISSUE THREAD

**Issue by deepankersharmaa** [prometheus-community/ipmi_exporter#84]
Getting below error while creating container using image.
Error: container_linux.go:370: starting container process caused: exec: "/bin/ipmi_exporter": permission denied: OCI permission denied

Can you please share docker image.

**Comment by bitfehler** [comment]
Thank you for your report. I am currently in a situation with limited access to computers. Once I get back (end of November) I will work on getting #83 into a working state. Then we'll be able to publish docker images like other exporters that are part of prometheus-community. Sorry for the delay. I'll keep this issue open as a reminder to check the docker images.

**Comment by bitfehler** [comment]
This was an issue with the documentation being obsolete after the move to community. See the updated instructions: https://github.com/prometheus-community/ipmi_exporter#building-a-docker-container
