### ISSUE TITLE
version information goes to stderr instead of stdout

### ISSUE THREAD

**Issue by mnohrthern** [prometheus-community/ipmi_exporter#97]
Hey guys,

during the rollout automation of the ipmi exporter, I've recognized that the output of

`ipmi_exporter --version`

is send to stderr. This behavior is different to the rest of the prometheus stack, like prometheus itself, alertmanager or node exporter. All of them send version infos to stdout. 

Is this intended? 

**expected behavior:**

* Version output goes to stdout

**observed behavior:**

* Version output goes to stderr

**Comment by bitfehler** [comment]
Thanks for pointing that out, I never noticed this
